### get category
GET http://15.165.198.243/api/v1/category/ HTTP/1.1
Content-Type: application/json
Authorization: JWT ACCESS TOKEN

### write category
POST http://15.165.198.243/api/v1/category/ HTTP/1.1
Content-Type: application/json
Authorization: JWT ACCESS TOKEN

{
  "name": "urLink",
  "is_favorited": false
}

### update category
PATCH   http://15.165.198.243/api/v1/category/83/ HTTP/1.1
Content-Type: application/json
Authorization: JWT ACCESS TOKEN

{
  "is_favorited": false
}

### Delete category
DELETE   http://15.165.198.243/api/v1/category/14/ HTTP/1.1
Content-Type: application/json
Authorization: JWT ACCESS TOKEN