export const MODAL_NAME = {
  TERMS_MODAL: 'TERMS_MODAL',
  REMOVE_USER_ALERT_MODAL: 'REMOVE_USER_ALERT_MODAL',
  DELETE_CATEGORY_ALERT_MODAL: 'DELETE_CATEGORY_ALERT_MODAL',
  UPDATE_CATEGORY_MODAL: 'UPDATE_CATEGORY_MODAL',
  ADD_CATEGORY_MODAL: 'ADD_CATEGORY_MODAL',
}

export const DRAG = {
  DRAG_STATUS: 'drag',
  DROP_STATUS: 'drop',
  LINK: 'link',
  CATEGORY: 'category',
}

export const DROP_ZONE = {
  LINK_DROP_ZONE: 'LINK_DROP_ZONE',
}
